spring.application.name=HelloWorld

server.port=8082

spring.datasource.url=jdbc:postgresql://ep-twilight-bread-aola5nyn.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_SYsU0F1KHmrn

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true